[ACL4SSR]
name=ACL4SSR
url=https://github.com/ACL4SSR/ACL4SSR
commit=6e27259b8625e360699c014f98f978ee7408c644
match=Clash/*.list|Clash/Ruleset/**

[ACL4SSR_config]
name=ACL4SSR
url=https://github.com/ACL4SSR/ACL4SSR
commit=6e27259b8625e360699c014f98f978ee7408c644
match=Clash/config/**
dest=base/config/
keep_tree=false

[NobyDa]
url=https://github.com/NobyDa/Script
commit=0b8d083d444f4476700cb9d5d059c07b42da85eb
match=Surge/*.list

[lhie1]
url=https://github.com/dler-io/Rules
commit=1bfdc7d39e329cab2d2c50d391a3faaadb6a7e30
match=Surge/Surge 3/Provider/**
